[package]
name = "tiny-ray"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.62"
log = "0.4.17"
fern = "0.6.1"
chrono = "0.4.22"
png = "0.17.5"
palette = "0.6.1"
rayon = "1.5.3"
