[package]
name = "tiny-ray"
version = "0.1.0"
edition = "2021"
license = " AGPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.89"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = [ "std", "env-filter", "chrono" ] }
clap = "4.5.23"
png = "0.17.15"
palette = "0.7.6"
rayon = "1.10.0"
rand = "0.8.5"
num_cpus = "1.16.0"
